import re

def clean_sentence(line):
    # replace - unicode - punctuation
    line = re.sub(r'\\"', r'"', line)
    line = re.sub(r'\\t', ' ', line)
    line = re.sub(r'，', r',', line)
    line = re.sub(r'。 *', r'. ', line)
    line = re.sub(r'、', r',', line)
    line = re.sub(r'”', r'"', line)
    line = re.sub(r'“', r'"', line)
    line = re.sub(r'∶', r':', line)
    line = re.sub(r'：', r':', line)
    line = re.sub(r'？', r'?', line)
    line = re.sub(r'《', r'"', line)
    line = re.sub(r'》', r'"', line)
    line = re.sub(r'）', r')', line)
    line = re.sub(r'！', r'!', line)
    line = re.sub(r'（', r'(', line)
    line = re.sub(r'；', r';', line)
    line = re.sub(r'１', r'"', line)
    line = re.sub(r'」', r'"', line)
    line = re.sub(r'「', r'"', line)
    line = re.sub(r'０', r'0', line)
    line = re.sub(r'３', r'3', line)
    line = re.sub(r'２', r'2', line)
    line = re.sub(r'５', r'5', line)
    line = re.sub(r'６', r'6', line)
    line = re.sub(r'９', r'9', line)
    line = re.sub(r'７', r'7', line)
    line = re.sub(r'８', r'8', line)
    line = re.sub(r'４', r'4', line)
    line = re.sub(r'． *', r'. ', line)
    line = re.sub(r'～', r'~', line)
    line = re.sub(r'’', '\'', line)
    line = re.sub(r'…', r'...', line)
    line = re.sub(r'━', r'-', line)
    line = re.sub(r'〈', r'<', line)
    line = re.sub(r'〉', r'>', line)
    line = re.sub(r'【', r'[', line)
    line = re.sub(r'】', r']', line)
    line = re.sub(r'％', r'%', line)

    # remove - non - printing - char
    line = re.sub(r'[\x00-\x09\x0B-\x1F\x7F-\x9F\xAD]', r' ', line)
    line = re.sub(r'[\u0600-\u0605\u2060-\u206f\u202a-\u202e\u200b-\u200f]', r' ', line)
    line = re.sub(r'[\ufeff\ufff9\ufffa\ufffb]', r' ', line)
    line = re.sub(r'[\ue000-\uf8ff]', r' ', line)

    # normalize - punctuation
    line = re.sub(r'\r', r'', line)
    line = re.sub(r'\(', r' (', line)
    line = re.sub(r'\)', r') ', line)
    line = re.sub(r' +', r' ', line)
    line = re.sub(r'\) ([\.\!\:\?\;\,])', r')\1', line)
    line = re.sub(r'\( ', r'(', line)
    line = re.sub(r' \)', r')', line)
    line = re.sub(r'(\d) \%', r'\1%', line)
    line = re.sub(r' :', r':', line)
    line = re.sub(r' ;', r';', line)
    line = re.sub(r'\`', '\'', line)
    line = re.sub(r'\'\'', r' " ', line)
    line = re.sub(r'„', r'"', line)
    line = re.sub(r'“', r'"', line)
    line = re.sub(r'”', r'"', line)
    line = re.sub(r'–', r'-', line)
    line = re.sub(r'—', r' - ', line)
    line = re.sub(r' +', r' ', line)
    line = re.sub(r'´', '\'', line)
    line = re.sub(r'([a-zA-Z])‘([a-zA-Z])', '\\1\'\\2', line)
    line = re.sub(r'([a-zA-Z])’([a-zA-Z])', '\\1\'\\2', line)
    line = re.sub(r'‘', r'"', line)
    line = re.sub(r'‚', r'"', line)
    line = re.sub(r'’', r'"', line)
    line = re.sub(r'\'\'', r'"', line)
    line = re.sub(r'´´', r'"', line)
    line = re.sub(r'…', r'...', line)
    line = re.sub(r' « ', r' "', line)
    line = re.sub(r'« ', r'"', line)
    line = re.sub(r'«', r'"', line)
    line = re.sub(r' » ', r'" ', line)
    line = re.sub(r' »', r'"', line)
    line = re.sub(r'»', r'"', line)
    line = re.sub(r' \%', r'%', line)
    line = re.sub(r'nº ', r'nº ', line)
    line = re.sub(r' :', r':', line)
    line = re.sub(r' ºC', r' ºC', line)
    line = re.sub(r' cm', r' cm', line)
    line = re.sub(r' \?', r'?', line)
    line = re.sub(r' \!', r'!', line)
    line = re.sub(r' ;', r';', line)
    line = re.sub(r', ', r', ', line)
    line = re.sub(r' +', r' ', line)
    line = re.sub(r'\"([,\.]+)', r'\1"', line)
    return line